{{- if .Values.api.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-api
  namespace: {{ .Release.Namespace }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.kargo: 'https://{{ .Values.api.host }}/dex/callback'
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.api.labels" . | nindent 4 }}
{{- end }}
