kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kargo-dex-server
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - secrets
      - configmaps