kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kargo-dex-server
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: kargo-dex-server
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kargo-dex-server
