{{- if and .Values.api.enabled .Values.api.oidc.enabled .Values.api.oidc.dex.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-dex-server
  namespace: {{ .Release.Namespace }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.kargo: 'https://{{ .Values.api.host }}/dex/callback'
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.dexServer.labels" . | nindent 4 }}
{{- end }}
